-- Generated by scripts/archive-replace-vocab.ts from vocab-archive-replace.json.
-- One statement: archives 32, inserts 32, checks 350 per level.
-- Any failed check raises an error and Postgres rolls back all of it.
do $$
declare n int;
begin
  update public.vocabulary v set is_archived = true
  from (values
      ('accelerate', 4),
      ('activate', 4),
      ('collaborate', 4),
      ('collaborative', 4),
      ('collectively', 4),
      ('efficiently', 4),
      ('focused', 4),
      ('historically', 4),
      ('hostile', 4),
      ('immune', 4),
      ('irony', 4),
      ('representation', 4),
      ('spontaneous', 4),
      ('timid', 4),
      ('verify', 4),
      ('authentic', 4),
      ('omit', 4),
      ('respectively', 4),
      ('comprehend', 5),
      ('cynical', 5),
      ('disciplined', 5),
      ('elaborate', 5),
      ('empathetic', 5),
      ('portray', 5),
      ('progressively', 5),
      ('systematically', 5),
      ('eccentric', 5),
      ('anarchy', 5),
      ('abbreviate', 5),
      ('initialize', 5),
      ('notably', 5),
      ('proactive', 5)
  ) a(word, lvl)
  where v.word = a.word and v.difficulty_level = a.lvl and not v.is_archived;
  get diagnostics n = row_count;
  if n <> 32 then raise exception 'archived % words, expected 32', n; end if;

  insert into public.vocabulary (word, hebrew_translation, definition, example_sentence, part_of_speech, category, difficulty_level)
  values
      ('benchmark', 'נקודת ייחוס; אמת מידה', 'A standard used to measure or judge other things', 'The test is a benchmark for comparing schools.', 'noun', 'general', 4),
      ('clout', 'השפעה; כוח', 'Power or influence, especially in politics or business', 'Large companies have considerable political clout.', 'noun', 'general', 4),
      ('conducive', 'מסייע ל-; תורם ל-', 'Making a particular result likely or possible', 'A quiet room is conducive to concentration.', 'adjective', 'general', 4),
      ('trajectory', 'מסלול; כיוון התפתחות', 'The path something follows, or the way it develops over time', 'The report describes the career trajectory of young doctors.', 'noun', 'general', 4),
      ('deprivation', 'מחסור; שלילה', 'The lack of something needed, such as food, sleep or rights', 'Sleep deprivation affects memory and mood.', 'noun', 'general', 4),
      ('disdain', 'בוז', 'The feeling that someone or something is not worth respect', 'The critic wrote about the film with open disdain.', 'noun', 'general', 4),
      ('dispel', 'להפיג; להפריך', 'To make a feeling or belief disappear', 'The study helped dispel several myths about diet.', 'verb', 'general', 4),
      ('disseminate', 'להפיץ', 'To spread information or knowledge widely', 'The results were disseminated through academic journals.', 'verb', 'general', 4),
      ('superficial', 'שטחי', 'Relating only to the surface, not deep or thorough', 'The report offers only a superficial analysis of the problem.', 'adjective', 'general', 4),
      ('embody', 'לגלם', 'To represent an idea or quality in a clear way', 'The new museum embodies the spirit of the city.', 'verb', 'general', 4),
      ('endemic', 'אנדמי; נפוץ באופן קבוע', 'Regularly found in a particular place or group', 'Malaria is endemic in parts of Africa.', 'adjective', 'general', 4),
      ('incremental', 'הדרגתי; מצטבר', 'Increasing gradually by small amounts', 'The company made incremental improvements to its product.', 'adjective', 'general', 4),
      ('notorious', 'ידוע לשמצה', 'Famous for something bad', 'The road is notorious for accidents.', 'adjective', 'general', 4),
      ('peripheral', 'שולי; היקפי', 'Not central or most important, or at the outer edge', 'The issue is peripheral to the main debate.', 'adjective', 'general', 4),
      ('plight', 'מצוקה', 'A difficult or dangerous situation', 'The article describes the plight of refugees.', 'noun', 'general', 4),
      ('onus', 'אחריות; נטל (הוכחה)', 'The responsibility or duty to do something', 'The onus is on the company to prove the product is safe.', 'noun', 'general', 4),
      ('skeptical', 'ספקני', 'Having doubts that something is true or useful', 'Many scientists remain skeptical about the new theory.', 'adjective', 'general', 4),
      ('succinct', 'תמציתי', 'Clearly expressed in few words', 'The report ends with a succinct summary.', 'adjective', 'general', 4),
      ('enervate', 'להתיש; להחליש', 'To make someone feel weak and tired', 'The long heat wave enervated the whole city.', 'verb', 'general', 5),
      ('anathema', 'תועבה; דבר שנוא', 'Something that someone strongly dislikes or disapproves of', 'Censorship is anathema to a free press.', 'noun', 'general', 5),
      ('cacophony', 'צרימה; רעש צורם', 'A loud, unpleasant mixture of sounds', 'A cacophony of car horns filled the street.', 'noun', 'general', 5),
      ('capitulate', 'להיכנע', 'To stop resisting and accept what someone demands', 'The government refused to capitulate to the strikers.', 'verb', 'general', 5),
      ('feckless', 'חסר אחריות; חסר תועלת', 'Lacking energy, ability or a sense of responsibility', 'Critics described the leadership as feckless.', 'adjective', 'general', 5),
      ('harangue', 'נאום תוכחה ארוך', 'A long, loud and angry speech that criticizes someone', 'The coach delivered a harangue after the defeat.', 'noun', 'general', 5),
      ('implacable', 'שאין לפייסו; עיקש', 'Impossible to calm, satisfy or stop', 'The rebels faced an implacable enemy.', 'adjective', 'general', 5),
      ('nefarious', 'נפשע; שפל', 'Wicked or criminal', 'The group was involved in several nefarious schemes.', 'adjective', 'general', 5),
      ('obstinate', 'עקשן', 'Refusing to change your opinion or behavior', 'The obstinate child refused to eat anything green.', 'adjective', 'general', 5),
      ('paucity', 'דלות; מיעוט', 'The state of having too little of something', 'The paucity of evidence made the case weak.', 'noun', 'general', 5),
      ('placate', 'לפייס; להרגיע', 'To make someone less angry by doing or saying something', 'The company offered refunds to placate angry customers.', 'verb', 'general', 5),
      ('prosaic', 'משעמם; חסר דמיון', 'Ordinary and dull, without imagination', 'The truth turned out to be far more prosaic.', 'adjective', 'general', 5),
      ('quandary', 'דילמה; מבוכה', 'A state of not knowing what to do in a difficult situation', 'The new law left many employers in a quandary.', 'noun', 'general', 5),
      ('vacillate', 'להסס; להתנדנד (בין אפשרויות)', 'To keep changing your opinion or decision', 'Voters vacillate between the two main parties.', 'verb', 'general', 5);
  get diagnostics n = row_count;
  if n <> 32 then raise exception 'inserted % words, expected 32', n; end if;

  update public.vocabulary set part_of_speech = 'adverb' where word = 'subjectively' and part_of_speech = 'adjective';
  get diagnostics n = row_count;
  if n <> 1 then raise exception 'part of speech fix for subjectively matched % rows, expected 1', n; end if;

  -- Every level must end with exactly 350 active words.
  if (select count(*) from (select difficulty_level from public.vocabulary where not is_archived group by difficulty_level having count(*) = 350) ok) <> 5 then
    raise exception 'level counts are not 350 each: %', (select string_agg(difficulty_level || '=' || c, ' ' order by difficulty_level) from (select difficulty_level, count(*) c from public.vocabulary where not is_archived group by 1) t);
  end if;
end $$;
